name: bloom-ci

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '40 7 * * 0'

jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-22.04, macos-latest]
          python: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
          include:
          - os: ubuntu-20.04
            python: 3.6
      name: bloom tests
      runs-on: ${{matrix.os}}

      steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install PyYAML argparse empy rosdep vcstools catkin-pkg python-dateutil packaging
          python -m pip install nose coverage pep8
      - name: Run tests
        run: |
          BLOOM_VERBOSE=1 python setup.py nosetests -s --tests test
